### ISSUE TITLE
App is not responsive to screen size changes

### ISSUE THREAD

**Issue by MarioTurco** [MarioTurco/GymUtility#2]
The app is not very responsive to screen resizes.
Ofther the app doesn't use all the space it has avaible, leaving some big blank spaces in the app window.

**Comment by klutchdev** [comment]
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Gym Utils</title>
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
    <link rel="stylesheet" href="index.css">
  </head>
  <body>
    <section class="section">
      <div class="container is-fluid">
        <div class="tabs is-centered">
          <ul>
            <li id="addTab" class="is-active"><a>Aggiungi</a></li>
            <li id="visualizeTab"><a>Visualizza</a></li>
            <li id="editTab"><a>Modifica</a></li>
            <li id="deleteTab"><a>Elimina</a></li>
            <li id="settingsTab"><a>Impostazioni</a></li>
          </ul>
        </div>
        <div class="field is-horizontal">
          <div class="field-label is-normal">
            <label class="label">Peso</label>
          </div>
          <input class="input" id="pesoText" type="number" placeholder="75">
        </div>
        <div class="field is-horizontal">
          <div class="field-label is-normal">
            <label class="label">Kcal</label>
          </div>
          <input class="input" id="kcalText" type="number" placeholder="1700">
        </div>
        <div class="field is-horizontal">
          <div class="field-label is-normal">
            <label class="label ">Data</label>
          </div>
          <input class="input" id="dataText" type="date" placeholder="gg/mm/aaaa">
        </div>
        <div class="field is-centered has-text-centered">
          <p class="control">
            <button id="addBtn" class="button is-success has-text-dark shadow">
            Aggiungi
            </button>
          </p>
        </div>
      </div>
    </section>
    <script defer src="logic.js"></script>
  </body>
</html>
```

```css
*,
html {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  margin: 0 auto;
  width: 100%;
}

.shadow {
  box-shadow: #03030356 2px 2px 6px;
  transition: all 400ms ease;
}

.shadow:hover {
  box-shadow: #03030356 1px 1px 4px;
  transition: all 400ms ease;
}

@media (max-width: 768px) {
  section {
    padding: 0;
    margin: 0 auto;
    width: 100%;
  }

  li {
    font-size: 0.65rem;
    font-weight: 600;
  }
}

@media (min-width: 769px) {
  section {
    width: 85%;
    margin: 0 auto;
  }

  li {
    font-size: 0.8rem;
    font-weight: 600;
  }
}

@media (min-width: 960px) {
  section {
    width: 75%;
    margin: 0 auto;
  }

  li {
    font-size: 0.9rem;
    font-weight: 600;
  }
}

@media (min-width: 1280px) {
  section {
    width: 60%;
    margin: 0 auto;
  }

  li {
    font-size: 1.2rem;
  }
}
```
