### ISSUE TITLE
Personalized Scroll bar

### ISSUE THREAD

**Issue by MarioTurco** [MarioTurco/GymUtility#6]
I would like to add a personalized scroll bar insted of the default windows one

**Comment by klutchdev** [comment]
Whats your favorite color?

**Comment by MarioTurco** [comment]
Umh, anything that could match the existing color scheme we already have.
But feel free to propose a new colore scheme if you like one!

**Comment by klutchdev** [comment]
I did blue for the time being because I wasn't sure, but it's really easy to change- just 1 setting in the css file

**Comment by klutchdev** [comment]
### Here's an example of some css you could add in the index.css file below the body style:
```css
/* ------/ The Scrollbar itself /------ */

body::-webkit-scrollbar {
  /*  Width */
  width: 1rem;
}

/*  ------/ Scrollbar "track" /------ */

body::-webkit-scrollbar-track {
  /*  Color */
  background: transparent;
}

/* -----/ Scrollbar "slider" button /----- */

body::-webkit-scrollbar-thumb {
  /*  Color */
  background: #0081d2;
  /*  Smooth the corners */
  border-radius: 6px;
}
```
### If you wanted to make it more dynamic, you could use css variables:
```css
:root {
  --scrollbar-width: 1rem;
  --scrollbar-bg: lightgrey;
  --scrollbar-button: forestgreen;
  --scrollbar-border-radius: 6px;
}

/* ... */

body::-webkit-scrollbar {
  width: var(--scrollbar-width);
}

body::-webkit-scrollbar-track {
  background: var(--scrollbar-bg);
}

body::-webkit-scrollbar-thumb {
  background: var(--scrollbar-button);
  border-radius: var(--scrollbar-border-radius);
}
```
@MarioTurco I don't know if that's the approach you want, but if you use variables you could make different scroll bar classes and allow the user to change the color "accent" theme of the app.
